/* PLAYER SETTINGS */
export const PLAYER_SPEED = 200;
export const PLAYER_JUMP_MULTIPLICATOR = 3;
export const PLAYER_FALL_MULTIPLICATOR = 0.7;
export const PLAYER_PLATFORM_BODY_WIDTH = 25;
export const PLAYER_PLATFORM_BODY_HEIGHT = 80;
export const PLAYER_TOPDOWN_BODY_WIDTH = 100;
export const PLAYER_TOPDOWN_BODY_HEIGHT = 100;
export const PLAYER_DISPLAY_WIDTH = 100;
export const PLAYER_DISPLAY_HEIGHT = 100;
export const PLAYER_MAX_HEALTH = 20;
export const PLAYER_CURRENT_HEALTH = 10;
export const SHIP_SPEED = 200;
export const SHIP_DISPLAY_WIDTH = 100;
export const SHIP_DISPLAY_HEIGHT = 100;
export const SHIP_TOPDOWN_BODY_WIDTH = 100;
export const SHIP_TOPDOWN_BODY_HEIGHT = 100;
export const SHIP_ROTATION_SPEED = 0.05;